version: '3.8'

services:
  spear:
    image: jcotton42/spear:v1
    environment:
      - PgHost=db
      - PgDatabase=spear
      - PgUsername=postgres
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=spear
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: null
