version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  spear:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
    # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    # build:
    #   context: .
    #   dockerfile: .devcontainer/Dockerfile
    image: mcr.microsoft.com/vscode/devcontainers/dotnet:0-7.0
    environment:
      - NUGET_XMLDOC_MODE=none
      - PgPassword=postgres

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached
      - ${HOME}/.microsoft/usersecrets:/home/vscode/.microsoft/usersecrets

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    environment:
      - POSTGRES_PASSWORD=postgres
  adminer:
    image: docker.io/adminer:4
