version: '3.8'

services:
  spear:
    image: spear-devenv
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick a version of .NET: 3.1, 5.0, 6.0
        VARIANT: "6.0"
        # Optional version of Node.js
        NODE_VERSION: "none"
    environment:
      - PgHost=db
      - PgDatabase=spear
      - PgUsername=postgres
      - PgPassword=postgres

    volumes:
      - .:/workspace:cached
      - ${HOME}/.microsoft/usersecrets:/home/vscode/.microsoft/usersecrets

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=spear

  adminer:
    image: adminer:4

volumes:
  postgres-data: null
