version: '3.8'

services:
  spear:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick a version of .NET: 3.1, 5.0, 6.0
        VARIANT: "6.0"
        # Optional version of Node.js
        NODE_VERSION: "none"
    environment:
      - PgPassword=postgres
    init: true
    volumes:
      - .:/workspace:cached
      - ${HOME}/.microsoft/usersecrets:/home/vscode/.microsoft/usersecrets
      - /var/run/docker.sock:/var/run/docker-host.sock

  db:
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer:4
